### ISSUE TITLE
Remove Tahakom domains (tawtheeq.sa)

### ISSUE THREAD

**Issue by diego-a-pf** [swrdfgd/RandomWebsite#1]
We are acting on behalf of our client, Tahakom found at tahakom.com. 
Our client requests that all references to its website and its subsidiaries be removed from its code, In this case the domain requested to be removed from your code is: tawtheeq.sa

Please let us know if you need more information so that this can be removed quickly.

Thank you.

**Comment by swrdfgd** [comment]
Alright

**Comment by swrdfgd** [comment]
Done. Please inform me if you find another website to remove.

**Comment by PHCITSecurity** [comment]
I am part of the IT Security Team for Forest County Potawatomi Tribe operating as Potawatomi Bingo Casino.  You have 2 of our domains listed through your repositories.  Please remove all instances of the following:  fcpotwatomi.com and paysbig.com.

Please let me know if you need more information to expediate this removal.  Thank you!
