### ISSUE TITLE
Remove Domain

### ISSUE THREAD

**Issue by bishalcpgn** [swrdfgd/RandomWebsite#18]
[site2032.js]

domain : f***.***.np

**Comment by swrdfgd** [comment]
please explain what is the domain name

Pada Min, 4 Feb 2024 pukul 23.58 bishalcpgn ***@***.***>
menulis:

**Comment by swrdfgd** [comment]
the site has been removed

**Comment by bishalcpgn** [comment]
It's still in [site2032.js](https://github.com/swrdfgd/RandomWebsite/blob/65e93523c4068dced65b6e3973e1deee38e4a9d7/site2032.js#L1201)

**Comment by swrdfgd** [comment]
is the number of * matches the number of the characters?

**Comment by swrdfgd** [comment]
is it contain the word "college"?

**Comment by bishalcpgn** [comment]
yah, it contains the exact word !

**Comment by swrdfgd** [comment]
the site has been removed
