### ISSUE TITLE
Domain Takedown Request

### ISSUE THREAD

**Issue by PHCITSecurity** [swrdfgd/RandomWebsite#2]
I am part of the IT Security Team for Forest County Potawatomi Tribe operating as Potawatomi Bingo Casino. You have 2 of our domains listed through your repositories. Please remove all instances of the following: fcpotwatomi.com and paysbig.com.

Please let me know if you need more information to expediate this removal. Thank you!

**Comment by swrdfgd** [comment]
Okay, please wait ^_^

**Comment by swrdfgd** [comment]
I don't find fcpotwatomi.com but I find paysbig.com. Will be removed soon.

**Comment by swrdfgd** [comment]
Okay, done remove the domain. Please check for typo and make new issue, since I can't find fcpotwatomi.com.
