### ISSUE TITLE
Domain Takedown Reqeust

### ISSUE THREAD

**Issue by PHCITSecurity** [swrdfgd/RandomWebsite#3]
I am part of the IT Security Team for Forest County Potawatomi Tribe operating as Potawatomi Bingo Casino. You have 1 of our domains listed through your repositories. Please remove all instances of the following:  paysbig.com.

Please let me know if you need more information to expediate this removal. Thank you!

**Comment by swrdfgd** [comment]
Hello, just want to inform you, I have already done remove the domain paysbig.com.
