### ISSUE TITLE
Removal of 'mdsol' domain

### ISSUE THREAD

**Issue by jseese-mdsol** [swrdfgd/RandomWebsite#5]
Hello,

This is my second request for removal of any mention of "mdsol" org/domain within this repository.

I will check again on Friday that it's been removed.

**Comment by swrdfgd** [comment]
Hello, I have already remove a domain name mdsol .com. Please tell me if there are any more domains need removal.

**Comment by swrdfgd** [comment]
Okay, I think this issue has been resolved.
